@startuml
class 读者{
姓名
学号
借书号
借书限额
已借图书数
可用限额
}

class 管理员{
账号
密码
性别
}

class 游客{
 注册账户
}

class 书库信息{
图书总量
余量
历史类
科学类
数术类
社会类
}
class 图书{
书名
ISBN
作者
出版社
总量
余量
}
class 借书记录{
借阅者
图书名
ISBN
借书时间
还书时间
超时时间
罚款金额
}
class 罚款规则{
计费价格
}

管理员 --> 读者 : 管理 >
管理员 ..> 书库信息 :管理 >
管理员->借书记录:记录
管理员-->罚款规则:管理
读者-->图书
读者->书库信息
读者--借书记录
游客-->书库信息:查看 >
图书-*书库信息
管理员<|- manage
object manage{
add();
deleted();
redit();
}
游客<|- resign
object resign{
setUsername();
setPassWord();
setEmail();
}

@enduml
